### ISSUE TITLE
Optional per-tag descriptive content

### ISSUE THREAD

**Issue by scruloose** [adityatelange/hugo-index#6]
I'm not confident I have the Hugo terminology right for this, but I think it's the `taxonomy term` `list` page…  Anyway, the page that comes up when you click on a tag, and shows the list of posts that have that tag.

It would be cool if there was a place to drop a Markdown file containing a little descriptive blurb introducing the topic of that particular tag, which would be pulled in by the template and appear above the list on the generated page. Presumably it would want to be optional, so the page for any tag that *doesn't* have that Markdown file would just omit it and render without errors.

Obviously, I can figure out how to do this on my own site, but I'm guessing that would mean overriding the whole tag-listing page template from Index, and if you think it's worthwhile to add as a feature of the theme itself, then I don't have to!

**Comment by adityatelange** [comment]
Good Idea, checkout here https://adityatelange.github.io/hugo-index/html/

![adityatelange github io_hugo-index_html_](https://github.com/adityatelange/hugo-index/assets/21258296/05f58bcd-6811-40fa-a336-e29143af4eac)
